"""make categoriese

Revision ID: 655060630538
Revises: 37d02eed07c0
Create Date: 2026-01-12 16:42:46.977599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

userrole = postgresql.ENUM('user', 'admin', name='userrole')
userrole.create(op.get_bind())


# revision identifiers, used by Alembic.
revision: str = '655060630538'
down_revision: Union[str, Sequence[str], None] = '37d02eed07c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.String(length=36), nullable=False))
    op.add_column('users', sa.Column('role', userrole, nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
